secrets_twitter=""
BEARER="AAAAAAAAAAAAAAAAAAAAAJ4vmwEAAAAAmESVioYl39NqZhNFTDwordWnLgo%3DhZQEl5ZdXN0nlW0Ql1skQXK7GXpF3pz7H0f8h81YspEl7XzI0e"
API_KEY="Q5iPC8Rfrbr34kbh4yimVsBRl"
API_TOKEN="e786tWSyTK3WnRiElaLgFfHBWBc58rCyzvJ0kxl6vatOZcAJrj"
ACCESS_TOKEN="1648053890560950272-9W0K5BlFcnn6C2OwU3lUwSSbM1y4Ay"
ACCESS_TOKEN_SECRET="cLIqPYoiSv5HI07gpnW23iR0MQ4a1aoABmgKQXhp3Dhrj"